title: Christina Frezynski
description: A portfolio of some of my work.
url: redfrez.github.io
baseurl: /frezfolio
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown
collections:
  projects:
    output: true